# Copyright (C) 2022 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build portable Linux binaries

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build-portable-binaries-linux.yml"
      - "cmake/**"
      - "external/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - "conanfile.py"
    tags:
      - 'v*.*.*'

  release:
    types: [ created ]

  workflow_dispatch:

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CONAN_REVISIONS_ENABLED: "1"
  CONAN_USER_HOME: "${{ github.workspace }}/conan-cache"
  CONAN_USER_HOME_SHORT: "${{ github.workspace }}/conan-cache/short"
  CONAN_V2_MODE: "1"
  CCACHE_DIR: "${{ github.workspace }}/ccache-cache"
  CCACHE_COMPRESSLEVEL: "13"
  CCACHE_MAXSIZE: "200M"

jobs:
  cache-test-datasets:
    uses: paulsengroup/modle/.github/workflows/cache-test-datasets.yml@main

  build-portable-binaries:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/paulsengroup/ci-docker-images/centos7-gcc-11:latest
      options: "-v ${{ github.workspace }}:${{ github.workspace }}"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate cache key
        id: cache-key
        run: |
          set -e
          set -u

          os="centos-7"
          compiler="gcc-11"
          hash="${{ hashFiles('conanfile.py', '.github/workflows/build-portable-binary-ubuntu.yml') }}"

          # This can be used by to always update a cache entry (useful e.g. for ccache)
          current_date="$(date '+%s')"

          conan_key_prefix="conan-$os-$compiler-$hash"
          ccache_key_prefix="ccache-$os-$compiler-$hash"

          echo "conan-key=$conan_key_prefix" >> $GITHUB_OUTPUT
          echo "conan-restore-key=$conan_key_prefix" >> $GITHUB_OUTPUT

          echo "ccache-key=${ccache_key_prefix}-${current_date}" >> $GITHUB_OUTPUT
          echo "ccache-restore-key=$ccache_key_prefix" >> $GITHUB_OUTPUT

      - name: Cache Conan packages
        id: cache-conan
        uses: actions/cache@v3
        with:
          key: ${{ steps.cache-key.outputs.conan-key }}
          restore-keys: ${{ steps.cache-key.outputs.conan-restore-key }}
          path: ${{ env.CONAN_USER_HOME }}

      - name: Clean Conan cache (pre-build)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan remove -f "*" --builds
          conan remove -f "*" --src
          conan remove -f "*" --system-reqs

      - name: Build conanfile.py
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          # Workaround GLIBCXX version mismatch
          printf '[requires]\nb2/4.9.3\n' > /tmp/conanfile.txt

          PATH="/opt/rh/devtoolset-11/root/usr/bin/:$PATH" \
          conan install /tmp/conanfile.txt --build=b2

          conan install conanfile.py          \
               --build=outdated               \
               --update                       \
               -s build_type=Release

      - name: Clean Conan cache (post-build)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan remove -f "*" --builds
          conan remove -f "*" --src
          conan remove -f "*" --system-reqs
          conan remove -f "*" --outdated

      - name: Cache Ccache folder
        uses: actions/cache@v3
        with:
          key: ${{ steps.cache-key.outputs.ccache-key }}
          restore-keys: ${{ steps.cache-key.outputs.ccache-restore-key }}
          path: ${{ env.CCACHE_DIR }}

      - name: Configure project
        working-directory: ${{ github.workspace }}
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          mkdir ${{ github.workspace }}/build
          cmake -DCMAKE_BUILD_TYPE=Release            \
                -DMODLE_ENABLE_TESTING=ON             \
                -DMODLE_DOWNLOAD_TEST_DATASET=OFF     \
                -DENABLE_DEVELOPER_MODE=OFF           \
                -DCMAKE_INSTALL_PREFIX="/tmp/modle/"  \
                -S "${{ github.workspace }}"          \
                -B "${{ github.workspace }}/build"

      - name: Build project
        working-directory: ${{ github.workspace }}
        run: cmake --build build -j $(nproc)

      - name: Print Ccache statistics
        run: ccache -s

      - name: Install project
        working-directory: ${{ github.workspace }}
        run: |
          cmake --install build/
          cp build/test/test_main /tmp/modle/bin

      - name: Inspect MoDLE version
        working-directory: /tmp/modle
        run: |
          bin/modle --version
          bin/modle_tools --version

      - name: Archive binaries
        working-directory: /tmp
        run: |
          tar -czf modle.tar.gz modle
          tar -tf modle.tar.gz

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: portable-bins
          if-no-files-found: error
          retention-days: 1
          path: /tmp/modle.tar.gz

  run-unit-tests:
    runs-on: ubuntu-latest
    needs: [build-portable-binaries, cache-test-datasets]
    container:
      image: centos:7
      options: "-v ${{ github.workspace }}:${{ github.workspace }}"

    steps:
      - uses: actions/checkout@v3

      - name: Download Binaries
        uses: actions/download-artifact@v3
        with:
          name: portable-bins

      - name: Download test datasets
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.cache-test-datasets.outputs.artifact-name }}

      - name: Extract binaries and test dataset
        run: |
          tar -xf modle.tar.gz
          tar -xf modle_test_data.tar.gz

      - name: Run unit tests
        run: modle/bin/test_main --durations=yes 'exclude:*SciPy*' 'exclude:*wCorr*'

  run-modle-integration-tests:
    runs-on: ubuntu-latest
    needs: [build-portable-binaries, cache-test-datasets]
    container:
      image: ghcr.io/${{ github.repository_owner }}/ci-docker-images/modle/ubuntu-22.04-cxx-clang-14:latest
      options: "-v ${{ github.workspace }}:${{ github.workspace }}"

    steps:
      - uses: actions/checkout@v3

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: portable-bins

      - name: Download test datasets
        id: test-dataset
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.cache-test-datasets.outputs.artifact-name }}

      - name: Extract binaries and test dataset
        run: |
          tar -xf modle.tar.gz
          tar -xf modle_test_data.tar.gz

      - name: Run modle integration test(s)
        working-directory: ${{ github.workspace }}/test/scripts
        run: ./modle_integration_test.sh ${{ github.workspace }}/modle/bin/modle

  run-modle-tools-integration-tests:
    runs-on: ubuntu-latest
    needs: [build-portable-binaries, cache-test-datasets]
    container:
      image: ghcr.io/${{ github.repository_owner }}/ci-docker-images/modle/ubuntu-22.04-cxx-clang-14:latest
      options: "-v ${{ github.workspace }}:${{ github.workspace }}"

    steps:
      - uses: actions/checkout@v3

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: portable-bins

      - name: Download test datasets
        id: test-dataset
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.cache-test-datasets.outputs.artifact-name }}

      - name: Extract binaries and test dataset
        run: |
          tar -xf modle.tar.gz
          tar -xf modle_test_data.tar.gz

      - name: Run modle_tools transform integration test(s)
        working-directory: ${{ github.workspace }}/test/scripts
        run: ./modle_tools_transform_integration_test.sh ${{ github.workspace }}/modle/bin/modle_tools

      - name: Run modle_tools evaluate integration test(s)
        working-directory: ${{ github.workspace }}/test/scripts
        run: ./modle_tools_eval_integration_test.sh ${{ github.workspace }}/modle/bin/modle_tools

  run-portability-test:
    runs-on: ubuntu-latest
    needs: build-portable-binaries
    strategy:
      matrix:
        image:
          - 'archlinux:base'
          - 'centos:7'
          - 'rockylinux:9'
          - 'fedora:34'
          - 'fedora:latest'
          - 'opensuse/leap:latest'
          - 'opensuse/tumbleweed:latest'
          - 'ubuntu:16.04'
          - 'ubuntu:latest'
      fail-fast: false

    container:
      image: ${{ matrix.image }}
      options: "-v ${{ github.workspace }}:${{ github.workspace }}"

    steps:
      - name: Install dependencies (Ubuntu)
        if: contains(matrix.image, 'ubuntu')
        run: |
          apt-get update
          apt-get install -y libstdc++6

      - name: Install dependencies (openSUSE)
        if: contains(matrix.image, 'opensuse')
        run: zypper install -y gzip libstdc++6 tar

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: portable-bins

      - name: Extract binaries
        run: tar -xf modle.tar.gz

      - name: Test modle
        working-directory: modle/bin/
        run: |
          ./modle --version
          ./modle --help

          ./modle sim --help

      - name: Test modle_tools
        working-directory: modle/bin/
        run: |
          ./modle_tools --version
          ./modle_tools --help

          ./modle_tools eval --help
          ./modle_tools transform --help

  publish-binaries:
    needs:
      - run-unit-tests
      - run-modle-integration-tests
      - run-modle-tools-integration-tests
      - run-portability-test

    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: portable-bins

      - name: Generate archive name
        id: archive-name
        run: |
          version="$(basename "$GITHUB_REF")"
          version="${version#v}"

          echo "name=modle-$version" >> $GITHUB_OUTPUT

      - name: Archive binaries
        run: |
          tar -xf modle.tar.gz
          rm modle/bin/test_main

          mv modle "${{ steps.archive-name.outputs.name }}"
          tar -cJf "${{ steps.archive-name.outputs.name }}.tar.xz" "${{ steps.archive-name.outputs.name }}"

          tar -tf "${{ steps.archive-name.outputs.name }}.tar.xz"

      - name: Upload Binaries
        if: github.event_name == 'release'
        uses: skx/github-action-publish-binaries@release-2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "${{ steps.archive-name.outputs.name }}.tar.xz"
