# Copyright (C) 2022 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Cache test datasets

on:
  workflow_call:
    outputs:
      artifact-name:
        description: "Test dataset artifact name"
        value: ${{ jobs.cache-test-datasets.outputs.cache-key }}
      cache-key:
        description: "Test dataset cache key"
        value: ${{ jobs.cache-test-datasets.outputs.cache-key }}

defaults:
  run:
    shell: bash

env:
  FETCH_TEST_DATASET_CMAKE: cmake/FetchTestDataset.cmake
  TEST_DATASET_PATH: test/data/modle_test_data.tar.xz

jobs:
  cache-test-datasets:
    name: Cache test datasets
    runs-on: ubuntu-latest

    outputs:
      cache-key: ${{ steps.generate-cache-key.outputs.key }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Generate cache key
      id: generate-cache-key
      run: |
        key="test-dataset-${{ hashFiles( 'cmake/FetchTestDataset.cmake' ) }}"

        echo "key=$key" >> $GITHUB_OUTPUT

    - name: Extract test dataset URL and checksum
      id: test-dataset
      run: |
        url="$(grep -F 'DOWNLOAD' "$FETCH_TEST_DATASET_CMAKE" | sed 's/.*DOWNLOAD[[:space:]]\+//')"
        checksum="$(grep -F 'EXPECTED_HASH' "$FETCH_TEST_DATASET_CMAKE" | sed 's/.*SHA512=//')"

        echo "url=$url" >> $GITHUB_OUTPUT
        echo "checksum=$checksum" >> $GITHUB_OUTPUT

    - name: Cache test datasets
      id: cache-dataset
      uses: actions/cache@v3
      with:
        key: ${{ steps.generate-cache-key.outputs.key }}
        path: ${{ env.TEST_DATASET_PATH }}

    - name: Download test dataset
      if: steps.cache-dataset.outputs.cache-hit != 'true'
      run: |
        src="${{ steps.test-dataset.outputs.url }}"
        dest="$TEST_DATASET_PATH"

        mkdir -p "$(dirname "$dest")"
        curl -L "$src" -o "$dest"

    - name: Checksum test dataset
      run: |
        echo "${{ steps.test-dataset.outputs.checksum }}  $TEST_DATASET_PATH" > checksum.sha512
        shasum -c checksum.sha512

    - name: Upload test dataset
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.generate-cache-key.outputs.key }}
        path: ${{ env.TEST_DATASET_PATH }}
        if-no-files-found: error
        retention-days: 1
