# Copyright (C) 2022 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: MacOS CI

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/macos-ci.yml"
      - "cmake/**"
      - "external/**"
      - "src/**"
      - "test/**"
      - "!test/scripts/devel/**"
      - "CMakeLists.txt"
      - "conanfile.txt"
    tags:
      - 'v*.*.*'

  pull_request:
    paths:
      - ".github/workflows/macos-ci.yml"
      - "cmake/**"
      - "external/**"
      - "src/**"
      - "test/**"
      - "!test/scripts/devel/**"
      - "CMakeLists.txt"
      - "conanfile.txt"

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CCACHE_DIR: "${{ github.workspace }}/ccache-cache"
  CCACHE_COMPRESSLEVEL: "13"
  CCACHE_MAXSIZE: "200M"
  CONAN_HOME: "${{ github.workspace }}/.conan2"
  HOMEBREW_NO_AUTO_UPDATE: "1"

defaults:
  run:
    shell: bash

jobs:
  cache-test-datasets:
    uses: paulsengroup/modle/.github/workflows/cache-test-datasets.yml@main


  ci:
    name: MacOS CI
    needs: cache-test-datasets
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { compiler-name: apple-clang, compiler-version: '13.0', os: 'macos-11', conan-ver: '2.0.*', cmake-ver: '3.26.*', build_type: Release, developer_mode: OFF }
          - { compiler-name: apple-clang, compiler-version: '14.0', os: 'macos-12', conan-ver: '2.0.*', cmake-ver: '3.26.*', build_type: Release, developer_mode: OFF }
          - { compiler-name: apple-clang, compiler-version: '14.0', os: 'macos-12', conan-ver: '2.0.*', cmake-ver: '3.26.*', build_type: Release, developer_mode: OFF }
          - { compiler-name: apple-clang, compiler-version: '14.0', os: 'macos-13', conan-ver: '2.0.*', cmake-ver: '3.26.*', build_type: Release, developer_mode: OFF }
          - { compiler-name: apple-clang, compiler-version: '14.0', os: 'macos-13', conan-ver: '2.0.*', cmake-ver: '3.26.*', build_type: Debug,   developer_mode: OFF }

    steps:
      - uses: actions/checkout@v3

      - name: Generate requirements.txt for pip
        run: |
          echo 'conan==${{ matrix.conan-ver }}' > requirements.txt
          echo 'cmake==${{ matrix.cmake-ver }}' >> requirements.txt

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install build deps
        run: |
          pip install -r requirements.txt
          brew install ccache

      - name: Detect number available CPUs
        run: |
          ncpus=$(python -c 'import multiprocessing as mp; print(mp.cpu_count())')

          echo "CMAKE_BUILD_PARALLEL_LEVEL=$ncpus" >> $GITHUB_ENV
          echo "CTEST_PARALLEL_LEVEL=$ncpus" >> $GITHUB_ENV

      - name: Generate cache key
        id: cache-key
        run: |
          set -u

          os="${{ matrix.os }}"
          compiler="${{ matrix.compiler-name }}"
          build_type="${{ matrix.build_type }}"

          conanfile_hash="${{ hashFiles('conanfile.txt') }}"
          workflow_hash="${{ hashFiles('.github/workflows/macos-ci.yml') }}"
          combined_hash="${{ hashFiles('conanfile.txt', '.github/workflows/macos-ci.yml') }}"

          # This can be used by to always update a cache entry (useful e.g. for ccache)
          current_date="$(date '+%s')"

          conan_key_prefix="conan-$os-$compiler-$conanfile_hash-$build_type"
          ccache_key_prefix="ccache-$os-$compiler-$conanfile_hash-$build_type"

          echo "conan-key=$conan_key_prefix" >> $GITHUB_OUTPUT
          echo "conan-restore-key=$conan_key_prefix" >> $GITHUB_OUTPUT

          echo "ccache-key=${ccache_key_prefix}-${current_date}" >> $GITHUB_OUTPUT
          echo "ccache-restore-key=$ccache_key_prefix" >> $GITHUB_OUTPUT

      - name: Cache Conan packages
        id: cache-conan
        uses: actions/cache@v3
        with:
          key: ${{ steps.cache-key.outputs.conan-key }}
          restore-keys: ${{ steps.cache-key.outputs.conan-restore-key }}
          path: ${{ env.CONAN_HOME }}

      - name: Configure Conan
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: conan profile detect --force

      - name: Clean Conan cache (pre-build)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan cache clean "*" --build
          conan cache clean "*" --download
          conan cache clean "*" --source
          conan remove --confirm "*"

      - name: Build conanfile.txt
        run: |
          conan install conanfile.txt                 \
               --build=missing                        \
               -pr default                            \
               -s build_type=${{ matrix.build_type }} \
               -s compiler.libcxx=libc++              \
               -s compiler.cppstd=17                  \
               --output-folder="${{ github.workspace }}/build"

      - name: Clean Conan cache (post-build)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan cache clean "*" --build
          conan cache clean "*" --download
          conan cache clean "*" --source

      - name: Configure project
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}          \
                -DCMAKE_PREFIX_PATH="${{ github.workspace }}/build"  \
                -DMODLE_ENABLE_TESTING=ON                            \
                -DMODLE_DOWNLOAD_TEST_DATASET=OFF                    \
                -DENABLE_DEVELOPER_MODE=${{ matrix.developer_mode }} \
                -DOPT_ENABLE_CLANG_TIDY=OFF                          \
                -DOPT_ENABLE_CPPCHECK=OFF                            \
                -S "${{ github.workspace }}"                         \
                -B "${{ github.workspace }}/build"

      - name: Cache Ccache folder
        uses: actions/cache@v3
        with:
          key: ${{ steps.cache-key.outputs.ccache-key }}
          restore-keys: ${{ steps.cache-key.outputs.ccache-restore-key }}
          path: ${{ env.CCACHE_DIR }}

      - name: Build project
        run: cmake --build ${{ github.workspace }}/build

      - name: Print Ccache statistics
        run: ccache -s

      - name: Download test datasets
        id: test-dataset
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.cache-test-datasets.outputs.artifact-name }}

      - name: Extract test dataset
        run: tar -xf modle_test_data.tar.xz

      - name: Run unit tests
        working-directory: ${{ github.workspace }}/build
        run: |
          ctest --test-dir .        \
                --schedule-random   \
                --output-on-failure \
                --no-tests=error    \
                --timeout 300

      - name: Inspect MoDLE version
        run: |
          ${{ github.workspace }}/build/src/modle/modle --version
          ${{ github.workspace }}/build/src/modle_tools/modle_tools --version


  macos-ci-status-check:
    name: Status Check (MacOS CI)
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [ ci ]
    steps:
      - name: Collect job results
        if: needs.ci.result != 'success'
        run: exit 1
